# 
# Synthesis run script generated by Vivado
# 

set_msg_config -id {HDL 9-1061} -limit 100000
set_msg_config -id {HDL 9-1654} -limit 100000
create_project -in_memory -part xc7a200tsbg484-1

set_param project.singleFileAddWarning.threshold 0
set_param project.compositeFile.enableAutoGeneration 0
set_param synth.vivado.isSynthRun true
set_property webtalk.parent_dir {C:/Users/Jash/Desktop/packaged joystick/ip_repo/edit_packaged_joystick_v1_0.cache/wt} [current_project]
set_property parent.project_path {C:/Users/Jash/Desktop/packaged joystick/ip_repo/edit_packaged_joystick_v1_0.xpr} [current_project]
set_property default_lib xil_defaultlib [current_project]
set_property target_language Verilog [current_project]
set_property board_part digilentinc.com:nexys_video:part0:1.1 [current_project]
set_property ip_repo_paths {{c:/Users/Jash/Desktop/packaged joystick/ip_repo/packaged_joystick_1.0}} [current_project]
read_verilog -library xil_defaultlib {
  {C:/Users/Jash/Desktop/packaged joystick/ip_repo/packaged_joystick_1.0/hdl/Binary_To_BCD.v}
  {C:/Users/Jash/Desktop/packaged joystick/ip_repo/packaged_joystick_1.0/hdl/ClkDiv_66_67kHz.v}
  {C:/Users/Jash/Desktop/packaged joystick/ip_repo/packaged_joystick_1.0/hdl/SPImode0.v}
  {C:/Users/Jash/Desktop/packaged joystick/ip_repo/packaged_joystick_1.0/hdl/spiCtrl.v}
  {C:/Users/Jash/Desktop/packaged joystick/ip_repo/packaged_joystick_1.0/hdl/ssdCtrl.v}
  {C:/Users/Jash/Desktop/packaged joystick/ip_repo/packaged_joystick_1.0/hdl/ClkDiv_5Hz.v}
  {C:/Users/Jash/Desktop/packaged joystick/ip_repo/packaged_joystick_1.0/hdl/PmodJSTK.v}
  {C:/Users/Jash/Desktop/packaged joystick/ip_repo/packaged_joystick_1.0/hdl/PmodJSTK_Demo.v}
  {C:/Users/Jash/Desktop/packaged joystick/ip_repo/packaged_joystick_1.0/hdl/packaged_joystick_v1_0_S00_AXI.v}
  {C:/Users/Jash/Desktop/packaged joystick/ip_repo/packaged_joystick_1.0/hdl/packaged_joystick_v1_0.v}
}
foreach dcp [get_files -quiet -all *.dcp] {
  set_property used_in_implementation false $dcp
}

synth_design -top packaged_joystick_v1_0 -part xc7a200tsbg484-1


write_checkpoint -force -noxdef packaged_joystick_v1_0.dcp

catch { report_utilization -file packaged_joystick_v1_0_utilization_synth.rpt -pb packaged_joystick_v1_0_utilization_synth.pb }
