# 
# Synthesis run script generated by Vivado
# 

set_msg_config -id {HDL 9-1061} -limit 100000
set_msg_config -id {HDL 9-1654} -limit 100000
set_msg_config -id {HDL-1065} -limit 10000
create_project -in_memory -part xc7a200tsbg484-1

set_param project.singleFileAddWarning.threshold 0
set_param project.compositeFile.enableAutoGeneration 0
set_param synth.vivado.isSynthRun true
set_property webtalk.parent_dir c:/xilinx/projects/stable_puck_detection/ip_repo/edit_stable_puck_detection_v1_0.cache/wt [current_project]
set_property parent.project_path c:/xilinx/projects/stable_puck_detection/ip_repo/edit_stable_puck_detection_v1_0.xpr [current_project]
set_property default_lib xil_defaultlib [current_project]
set_property target_language Verilog [current_project]
set_property ip_repo_paths c:/Xilinx/Projects/stable_puck_detection/ip_repo/stable_puck_detection_1.0 [current_project]
read_verilog -library xil_defaultlib {
  c:/Xilinx/Projects/stable_puck_detection/ip_repo/stable_puck_detection_1.0/hdl/stable_puck_detection_v1_0_S00_AXI.v
  c:/Xilinx/Projects/stable_puck_detection/ip_repo/stable_puck_detection_1.0/hdl/stable_puck_detection_v1_0_S00_AXIS.v
  c:/Xilinx/Projects/stable_puck_detection/ip_repo/stable_puck_detection_1.0/hdl/stable_puck_detection_v1_0_M00_AXIS.v
  c:/Xilinx/Projects/stable_puck_detection/ip_repo/stable_puck_detection_1.0/hdl/stable_puck_detection_v1_0.v
}
foreach dcp [get_files -quiet -all *.dcp] {
  set_property used_in_implementation false $dcp
}

synth_design -top stable_puck_detection_v1_0 -part xc7a200tsbg484-1


write_checkpoint -force -noxdef stable_puck_detection_v1_0.dcp

catch { report_utilization -file stable_puck_detection_v1_0_utilization_synth.rpt -pb stable_puck_detection_v1_0_utilization_synth.pb }
